---
language: [ ruby, node_js ]
rvm: [ 2.1.1 ]
node_js: [ 0.10 ]

before_script:
  - npm install bower -g
  - bower install

before_install:
  - 'echo ''gem: --no-document'' > ~/.gemrc'

install:
  - bundle update

script: bundle exec rake travis

# Set the branch that will be built and published to GitHub pages.
branches:
  only:
    - project-site

# Create a GitHub Personal Access Token.
# Install the travis gem.
# Run the command below (fill in your name, email, and token):
# $ travis encrypt 'GIT_NAME="Your Name" GIT_EMAIL=you@example.com GH_TOKEN=token'
# Replace the value of secure with your generated value.
env:
  - secure: "hezCcOPJPAgVC0JauSCz9iFKIcpybXbVN/5vpLMGUUdNPCDti3SpdFAetn0hkwPPp1JnBMgBcmkhlMifhqCRM39qSwX01ke45/MHDoiKCi5sAYbNvd18S6YnpcsY7KQ/qi1o2HUNMu5Nj+ux9Gh9gVWmQacKhe/FeOKRTZA7lFE="
