assets:
  sources:
    - _assets/images
    - _assets/javascripts
    - _assets/stylesheets
    - bower_components
  cache: true
  compress:
    css: ""
    js: ""

google_analytics: false
piwik: false
