name: Site Name
markdown: redcarpet
pygments: true

exclude: [ 'CHANGELOG.md', 'LICENSE.txt', 'README.md', 'VERSION', 'Gemfile.lock', 'Gemfile', 'Rakefile' ]

assets:
  compress:
    css: sass
    js: uglifier

# Uncomment below to enable deploy.
# :deploy:
#   # either :rsync or :sftp
#   :protocol: :rsync
#   # domain name
#   :server: example.com
#   # remote username
#   :user: www
#   # remote port
#   :port: 22
#   # path to remote folder where contents of _site should go
#   # must have trailing slash
#   :path: /var/www/example.com/htdocs/

# Uncomment below to enable responsive images.
# picture:
#   source: pictures/_fullsize
#   output: pictures
#   markup: 'interchange'
#   presets:
#     default:
#       source_medium:
#         media: "(min-width: 40em)"
#         width: "600"
#       source_default:
#         width: "500"
