---
shipLabelOrder:
  - ship type
  - alliance
  - corporation
  - pilot name
  - ship name
  - null

shipLabels:
  - - null
    - - - post
        - ''
      - - pre
        - '['
      - - state
        - 0
      - - type
        - null
  - - alliance
    - - - post
        - '}'
      - - pre
        - ' {'
      - - state
        - 1
      - - type
        - alliance
  - - corporation
    - - - post
        - ']'
      - - pre
        - ' ['
      - - state
        - 1
      - - type
        - corporation
  - - pilot name
    - - - post
        - </b></color>
      - - pre
        - '  <color=0xFFFFFFFF><b>'
      - - state
        - 1
      - - type
        - pilot name
  - - ship name
    - - - post
        - '<fontsize=11><color=0xFFFEFF6F><b>  '
      - - pre
        - '  '
      - - state
        - 1
      - - type
        - ship name
  - - ship type
    - - - post
        - </b></color></fontsize>
      - - pre
        - <fontsize=11><color=0xFFF5DEB3><b>
      - - state
        - 1
      - - type
        - ship type
