---
- name: ✈
  color: FFFFBB33
  overview: travel
  bracket: brackets-all

- name: primary
  color: FFFF4444
  overview: hostile-minimal
  bracket: brackets-all

- name: tactical
  color: FF99CC00
  overview: friendly-ships
  bracket: brackets-all

- name: auxiliary
  color: FFAA66CC
  overview: extra-loot
  bracket: brackets-all

- name: disengage
  color: FF33B5E5
  overview: extra-warpout
  bracket: brackets-all
