---
columnOrder:
  - ICON
  - DISTANCE
  - NAME
  - TYPE
  - TAG
  - CORPORATION
  - ALLIANCE
  - FACTION
  - MILITIA
  - SIZE
  - VELOCITY
  - RADIALVELOCITY
  - TRANSVERSALVELOCITY
  - ANGULARVELOCITY

overviewColumns:
  - ALLIANCE
  - ANGULARVELOCITY
  - CORPORATION
  - DISTANCE
  - ICON
  - NAME
  - RADIALVELOCITY
  - TRANSVERSALVELOCITY
  - TYPE
  - VELOCITY
